# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tahara/ohehe

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tahara/ohehe

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tahara/ohehe/CMakeFiles /home/tahara/ohehe/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tahara/ohehe/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bookstore

# Build rule for target.
bookstore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bookstore
.PHONY : bookstore

# fast build rule for target.
bookstore/fast:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/build
.PHONY : bookstore/fast

CommandReader.o: CommandReader.cpp.o

.PHONY : CommandReader.o

# target to build an object file
CommandReader.cpp.o:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/CommandReader.cpp.o
.PHONY : CommandReader.cpp.o

CommandReader.i: CommandReader.cpp.i

.PHONY : CommandReader.i

# target to preprocess a source file
CommandReader.cpp.i:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/CommandReader.cpp.i
.PHONY : CommandReader.cpp.i

CommandReader.s: CommandReader.cpp.s

.PHONY : CommandReader.s

# target to generate assembly for a file
CommandReader.cpp.s:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/CommandReader.cpp.s
.PHONY : CommandReader.cpp.s

Controller/BookController.o: Controller/BookController.cpp.o

.PHONY : Controller/BookController.o

# target to build an object file
Controller/BookController.cpp.o:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/Controller/BookController.cpp.o
.PHONY : Controller/BookController.cpp.o

Controller/BookController.i: Controller/BookController.cpp.i

.PHONY : Controller/BookController.i

# target to preprocess a source file
Controller/BookController.cpp.i:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/Controller/BookController.cpp.i
.PHONY : Controller/BookController.cpp.i

Controller/BookController.s: Controller/BookController.cpp.s

.PHONY : Controller/BookController.s

# target to generate assembly for a file
Controller/BookController.cpp.s:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/Controller/BookController.cpp.s
.PHONY : Controller/BookController.cpp.s

Controller/UserController.o: Controller/UserController.cpp.o

.PHONY : Controller/UserController.o

# target to build an object file
Controller/UserController.cpp.o:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/Controller/UserController.cpp.o
.PHONY : Controller/UserController.cpp.o

Controller/UserController.i: Controller/UserController.cpp.i

.PHONY : Controller/UserController.i

# target to preprocess a source file
Controller/UserController.cpp.i:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/Controller/UserController.cpp.i
.PHONY : Controller/UserController.cpp.i

Controller/UserController.s: Controller/UserController.cpp.s

.PHONY : Controller/UserController.s

# target to generate assembly for a file
Controller/UserController.cpp.s:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/Controller/UserController.cpp.s
.PHONY : Controller/UserController.cpp.s

DB/BLL.o: DB/BLL.cpp.o

.PHONY : DB/BLL.o

# target to build an object file
DB/BLL.cpp.o:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/DB/BLL.cpp.o
.PHONY : DB/BLL.cpp.o

DB/BLL.i: DB/BLL.cpp.i

.PHONY : DB/BLL.i

# target to preprocess a source file
DB/BLL.cpp.i:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/DB/BLL.cpp.i
.PHONY : DB/BLL.cpp.i

DB/BLL.s: DB/BLL.cpp.s

.PHONY : DB/BLL.s

# target to generate assembly for a file
DB/BLL.cpp.s:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/DB/BLL.cpp.s
.PHONY : DB/BLL.cpp.s

DB/Book.o: DB/Book.cpp.o

.PHONY : DB/Book.o

# target to build an object file
DB/Book.cpp.o:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/DB/Book.cpp.o
.PHONY : DB/Book.cpp.o

DB/Book.i: DB/Book.cpp.i

.PHONY : DB/Book.i

# target to preprocess a source file
DB/Book.cpp.i:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/DB/Book.cpp.i
.PHONY : DB/Book.cpp.i

DB/Book.s: DB/Book.cpp.s

.PHONY : DB/Book.s

# target to generate assembly for a file
DB/Book.cpp.s:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/DB/Book.cpp.s
.PHONY : DB/Book.cpp.s

DB/Refer.o: DB/Refer.cpp.o

.PHONY : DB/Refer.o

# target to build an object file
DB/Refer.cpp.o:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/DB/Refer.cpp.o
.PHONY : DB/Refer.cpp.o

DB/Refer.i: DB/Refer.cpp.i

.PHONY : DB/Refer.i

# target to preprocess a source file
DB/Refer.cpp.i:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/DB/Refer.cpp.i
.PHONY : DB/Refer.cpp.i

DB/Refer.s: DB/Refer.cpp.s

.PHONY : DB/Refer.s

# target to generate assembly for a file
DB/Refer.cpp.s:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/DB/Refer.cpp.s
.PHONY : DB/Refer.cpp.s

DB/User.o: DB/User.cpp.o

.PHONY : DB/User.o

# target to build an object file
DB/User.cpp.o:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/DB/User.cpp.o
.PHONY : DB/User.cpp.o

DB/User.i: DB/User.cpp.i

.PHONY : DB/User.i

# target to preprocess a source file
DB/User.cpp.i:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/DB/User.cpp.i
.PHONY : DB/User.cpp.i

DB/User.s: DB/User.cpp.s

.PHONY : DB/User.s

# target to generate assembly for a file
DB/User.cpp.s:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/DB/User.cpp.s
.PHONY : DB/User.cpp.s

Reporter/Command.o: Reporter/Command.cpp.o

.PHONY : Reporter/Command.o

# target to build an object file
Reporter/Command.cpp.o:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/Reporter/Command.cpp.o
.PHONY : Reporter/Command.cpp.o

Reporter/Command.i: Reporter/Command.cpp.i

.PHONY : Reporter/Command.i

# target to preprocess a source file
Reporter/Command.cpp.i:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/Reporter/Command.cpp.i
.PHONY : Reporter/Command.cpp.i

Reporter/Command.s: Reporter/Command.cpp.s

.PHONY : Reporter/Command.s

# target to generate assembly for a file
Reporter/Command.cpp.s:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/Reporter/Command.cpp.s
.PHONY : Reporter/Command.cpp.s

Reporter/Finance.o: Reporter/Finance.cpp.o

.PHONY : Reporter/Finance.o

# target to build an object file
Reporter/Finance.cpp.o:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/Reporter/Finance.cpp.o
.PHONY : Reporter/Finance.cpp.o

Reporter/Finance.i: Reporter/Finance.cpp.i

.PHONY : Reporter/Finance.i

# target to preprocess a source file
Reporter/Finance.cpp.i:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/Reporter/Finance.cpp.i
.PHONY : Reporter/Finance.cpp.i

Reporter/Finance.s: Reporter/Finance.cpp.s

.PHONY : Reporter/Finance.s

# target to generate assembly for a file
Reporter/Finance.cpp.s:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/Reporter/Finance.cpp.s
.PHONY : Reporter/Finance.cpp.s

Reporter/Reporter.o: Reporter/Reporter.cpp.o

.PHONY : Reporter/Reporter.o

# target to build an object file
Reporter/Reporter.cpp.o:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/Reporter/Reporter.cpp.o
.PHONY : Reporter/Reporter.cpp.o

Reporter/Reporter.i: Reporter/Reporter.cpp.i

.PHONY : Reporter/Reporter.i

# target to preprocess a source file
Reporter/Reporter.cpp.i:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/Reporter/Reporter.cpp.i
.PHONY : Reporter/Reporter.cpp.i

Reporter/Reporter.s: Reporter/Reporter.cpp.s

.PHONY : Reporter/Reporter.s

# target to generate assembly for a file
Reporter/Reporter.cpp.s:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/Reporter/Reporter.cpp.s
.PHONY : Reporter/Reporter.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/bookstore.dir/build.make CMakeFiles/bookstore.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... bookstore"
	@echo "... edit_cache"
	@echo "... CommandReader.o"
	@echo "... CommandReader.i"
	@echo "... CommandReader.s"
	@echo "... Controller/BookController.o"
	@echo "... Controller/BookController.i"
	@echo "... Controller/BookController.s"
	@echo "... Controller/UserController.o"
	@echo "... Controller/UserController.i"
	@echo "... Controller/UserController.s"
	@echo "... DB/BLL.o"
	@echo "... DB/BLL.i"
	@echo "... DB/BLL.s"
	@echo "... DB/Book.o"
	@echo "... DB/Book.i"
	@echo "... DB/Book.s"
	@echo "... DB/Refer.o"
	@echo "... DB/Refer.i"
	@echo "... DB/Refer.s"
	@echo "... DB/User.o"
	@echo "... DB/User.i"
	@echo "... DB/User.s"
	@echo "... Reporter/Command.o"
	@echo "... Reporter/Command.i"
	@echo "... Reporter/Command.s"
	@echo "... Reporter/Finance.o"
	@echo "... Reporter/Finance.i"
	@echo "... Reporter/Finance.s"
	@echo "... Reporter/Reporter.o"
	@echo "... Reporter/Reporter.i"
	@echo "... Reporter/Reporter.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

